name: test-x86_64-windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        target: [
          x86_64-windows-gnu,
          x86_64-windows,
        ]
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.os }}, ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.3357+c44f4501e

      - name: Run Tests
        run: zig build test -Dtarget=${{ matrix.target }}